language: cpp
dist: trusty
os: linux
addons:
         apt:
                packages:
                        - g++-7
script:
        - CXX=/usr/bin/g++-7 C=/usr/bin/gcc-7 cmake .

after_success:
        - echo "success"

after_failure:
        - echo "failure"        
