palindrome: palindrome.cpp
	g++ palindrome.cpp -o main -Wall -Wextra -Werror -Wpedantic -O2 --std=c++17

debug:
	g++ palindrome.cpp -o main -Wall -Wextra -Werror -Wpedantic -g --std=c++17

clean:
	rm palindrome
